# Generated by Django 5.2.8 on 2025-11-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userstory_productbacklogitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
