# Generated by Django 5.2.8 on 2025-11-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklogitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_backlog', to='api.project'),
        ),
    ]
