# Generated by Django 5.2.8 on 2025-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sprint_productbacklogitem_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='increment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='team',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='tech',
            field=models.TextField(blank=True),
        ),
    ]
