# Generated by Django 5.2.8 on 2025-11-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sprint_increment_sprint_objective_sprint_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planejada'), ('ACTIVE', 'Ativa'), ('COMPLETED', 'Concluída')], default='PLANNED', max_length=10),
        ),
    ]
