# Generated by Django 5.2.8 on 2025-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('CONCLUDED', 'Concluído')], default='ACTIVE', max_length=12),
            preserve_default=False,
        ),
    ]
