# Generated by Django 5.2.8 on 2025-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_status_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('CONCLUDED', 'Concluído')], default='ACTIVE', max_length=12),
        ),
    ]
